version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skate-store
    environment:
      - NODE_ENV=production
      - PORT=80 
    ports:
      - '80:80' 
    restart: unless-stopped
